channels:
  - conda-forge
dependencies:
  - conda-forge::python>=3.12.3
  - conda-forge::blas=*=accelerate
  - conda-forge::libblas=*=*accelerate
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::mne
  - conda-forge::mne-qt-browser
  - conda-forge::autoreject
  - conda-forge::pytorch
  - conda-forge::ipympl
  - conda-forge::mnelab
  - ipykernel
  - python-dotenv
  - seaborn
  - pip
  - pyarrow
  - polars
  - pyprep
  - pyopengl
  - onnxruntime
  - flit
  - pip:
    - scipy>=1.14.0rc2
    - mne_bids
    - specparam>=2.0.0rc2
    - great_tables
    - mne-bids-pipeline
    - git+https://github.com/jackz314/eeglabio.git
    - mne_icalabel
    - meegkit
    - papermill
    - jupyterlab-quarto
    - https://github.com/hoechenberger/mne-python-stubs/archive/refs/heads/main.zip


