channels:
  - conda-forge
dependencies:
  - conda-forge::python>=3.13.9
  - conda-forge::numpy
  - conda-forge::libblas=*=*accelerate
  - conda-forge::pandas
  - conda-forge::mne-qt-browser
  - conda-forge::autoreject
  - conda-forge::pytorch
  - conda-forge::ipympl
  - conda-forge::mnelab
  - conda-forge::mne-icalabel
  - conda-forge::pyopengl
  - conda-forge::onnxruntime
  - conda-forge:mne
  - conda-forge:numba
  - conda-forge::mne-bids
  - conda-forge::scipy
  - conda-forge::mne-bids-pipeline
  - conda-forge::eeglabio
  - conda-forge::papermill
  - conda-forge::meegkit
  - ipykernel
  - python-dotenv
  - seaborn
  - pip
  - pyarrow
  - polars
  - pyprep
  - great_tables
  - pytest
  - plotnine
  - polars
  - pip:
      - specparam>=2.0.0rc2 
      - -e ./src/spectral[test] --config-settings editable_mode=compat
      - files-to-prompt
      - marimo
      - git+https://github.com/mne-tools/mne-denoise.git

