[project]
name = "psd-paths"
version = "0.1.0"
description = "Analysis of EEG PATHS project data"
readme = "README.md"
requires-python = ">=3.13.15"
dependencies = [
    "mne",
    "polars",
    "plotnine",
    "specparam>=2.0.0rc6",
    "pyrasa",
    "openneuro-py",
    "pandas",
    "matplotlib",
    "numpy",
    "scipy",
    "ipywidgets",
    "eeg-spectral",
    "bids>=0.0",
    "mne-bids>=0.17.0",
    "toml>=0.10.2",
    "pyzmq>=27.1.0",
    "eeglabio",
    "meegkit",
    "mne-bids-pipeline",
    "pyprep",
    "pyzaplineplus",
    "autoreject",
    "gedai",
    "pyriemann",
    "mne-icalabel[stubs]",
    "papermill",
    "jsonschema-specifications",
    "sf-hamilton[visualization]",
    "nbstripout",
    "pre-commit",
    "variable-inspector",
    "ipykernel",
    "notebook",
    "ipympl",
    "mne-bids"
]

[project.optional-dependencies]
dev = ["jupytext", "pip", "scipy-stubs", "mne[full-pyqt6]"]

[tool.uv]
package = false
link-mode = "copy"



[tool.uv.sources]
eeg-spectral = { path = "src/eeg-spectral", editable = true }
gedai = { git = "https://github.com/neurotuning/gedai" }

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.black]
line-length = 88
target-version = ['py313']
