[paths]
project_root = "/Users/daniel/PhD/Projects/psd-paths"
path_raw_mff = "/Users/daniel/PhD/Projects/psd-paths/data/source/DATI_PATHS/Raw_data"
path_raw_bids = "/Users/daniel/PhD/Projects/psd-path/data/raw/"

[experiment]
# Add any experiment-specific settings here
task = "rest" # or whatever your task is

[subjects]
# List of valid subject IDs if you want to validate
valid_ids = ["001", "002", "003"]

[preprocessing]
channels_to_remove = [
    "E67",
    "E73",
    "E82",
    "E91",
    "E92",
    "E102",
    "E111",
    "E120",
    "E133",
    "E145",
    "E165",
    "E174",
    "E187",
    "E199",
    "E208",
    "E209",
    "E216",
    "E217",
    "E218",
    "E219",
    "E225",
    "E226",
    "E227",
    "E228",
    "E229",
    "E230",
    "E231",
    "E232",
    "E233",
    "E234",
    "E235",
    "E236",
    "E237",
    "E238",
    "E239",
    "E240",
    "E241",
    "E242",
    "E243",
    "E244",
    "E245",
    "E246",
    "E247",
    "E248",
    "E249",
    "E250",
    "E251",
    "E252",
    "E253",
    "E254",
    "E255",
    "E256",
]
